#!/bin/bash

sudo bash -c "
	sed -i -e 's/^ConditionVirtualization=!container$/# ConditionVirtualization=!container/g' /usr/lib/systemd/system/systemd-timesyncd.service
	systemctl daemon-reload
	systemctl restart systemd-timesyncd.service
"
